import type { Metadata } from "next";
import AuthProvider from "@/context/AuthProvider";
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${inter.className}`}
      >

          {children}
          <Toaster/>
      </body>
        </AuthProvider>
    </html>
  );
}